#!/usr/bin/env python3
import argparse
import os
import pandas as pd
import matplotlib.pyplot as plt
from bonding_plot_utils import setup_academic_style, save_plot

def plot_drift_rate(csv_path, output_dir):
    # Read the drift_monitor output CSV
    df = pd.read_csv(csv_path)
    
    # Required columns: elapsed_s,device_0_pps_ticks,device_1_pps_ticks,delta_ticks,delta_us,drift_ppm
    if "elapsed_s" not in df.columns or "drift_ppm" not in df.columns:
        raise ValueError("CSV missing required columns: elapsed_s, drift_ppm")
    
    setup_academic_style()
    
    # Figure 9: Drift Rate Over Time
    fig, ax = plt.subplots()
    
    elapsed_time_h = df["elapsed_s"] / 3600.0
    
    ax.plot(elapsed_time_h, df["drift_ppm"])
    
    ax.set_title("Drift Rate Over Time")
    ax.set_xlabel("Time (Hours)")
    ax.set_ylabel("Drift Rate (ppm)")
    
    save_plot(fig, "fig09_drift_rate", output_dir)
    plt.close(fig)

def main():
    parser = argparse.ArgumentParser(description="USRP Clock Drift Analysis")
    parser.add_argument("--input-csv", required=True, help="Path to drift_log.csv generated by drift_monitor")
    parser.add_argument("--output-dir", required=True, help="Directory to save output plots")
    
    args = parser.parse_args()
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    print(f"Reading drift data from {args.input_csv}...")
    plot_drift_rate(args.input_csv, args.output_dir)
    print(f"Figure 9 saved to {args.output_dir}")

if __name__ == "__main__":
    main()
